guide/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('tactics/counter-tactics/', views.counter_tactics, name='counter-tactics'),
    path('tactics/overall-tactics/', views.overall_tactics, name='overall-tactics'),
    path('tactics/<title>/', views.counter_tactic_detail, name='tactics-detail'),
    path('beginners_guide/', views.beginners_guide, name='beginners_guide'),
    path('players/', views.players, name='players'),
    path('tips/', views.tips, name='tips'),
    path('terms_of_use/', views.terms_of_use, name='terms_of_use'),
    path('thank_you/', views.thank_you, name='thank_you'),

]

main/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('guide.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guide/models.py
from django.db import models


class Sideshow(models.Model):
    image = models.ImageField(default="banner.png", upload_to="sideshow_pics")
    title = models.CharField(max_length=70)
    content = models.CharField(max_length=200, help_text="Put //...// around a word if you wnat to make it bold")
    link = models.CharField(max_length=60)

    def __str__(self):
        return self.title


class ThankYou(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return f"Thank you ({self.name})"


class Tactic(models.Model):
    formation_text = models.CharField(max_length=50, help_text="Put //...// around a word if you wnat to make it bold")
    formation_image = models.ImageField(upload_to="tactics/formations")

    style_of_play_text = models.CharField(max_length=50, help_text="Put //...// around a word if you wnat to make it bold")
    style_of_play_image = models.ImageField(upload_to="tactics/style_of_play")

    line_tactics_text = models.CharField(max_length=50, help_text="Put //...// around a word if you wnat to make it bold")
    line_tactics_image = models.ImageField(upload_to="tactics/line_tactics")

    marking_offside_text = models.CharField(max_length=50, help_text="Put //...// around a word if you wnat to make it bold")
    marking_offside_image = models.ImageField(upload_to="tactics/marking_offside")

    tackling_index_text = models.CharField(max_length=50, help_text="Put //...// around a word if you wnat to make it bold")
    tackling_index_image = models.ImageField(upload_to="tactics/tackling_index")

    class Meta:
        abstract = True


class CounterTactic(models.Model):
    title = models.CharField(max_length=30)
    thumbnail = models.ImageField(upload_to="tactics/thumbnail", blank=True, null=True)

    def __str__(self):
        return self.title


class CounterTacticWeaker(Tactic):
    title = models.ForeignKey(CounterTactic, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} (weaker opponent)"

    class Meta:
        verbose_name_plural = 'Counter tactic (weaker opponent)'


class CounterTacticStronger(Tactic):
    title = models.ForeignKey(CounterTactic, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title} (stronger opponent)"

    class Meta:
        verbose_name_plural = 'Counter tactic (stronger opponent)'


class BestTactic(Tactic):
    title = models.CharField(max_length=80)

    def __str__(self):
        return self.title


class BeginnerTip(models.Model):
    title = models.CharField(max_length=40)
    image = models.ImageField(upload_to="beginner_tips_images")
    content = models.CharField(max_length=1000, help_text="BOLD: //x// to make x bold ................. "
                                                          "LINK: --x@/link@-- to go page link with text x..................."
                                                          "NEXT LINE: ==")

    def __str__(self):
        return self.title


class PlayerGroup(models.Model):
    title = models.CharField(max_length=50)
    keywords = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Player(models.Model):
    group = models.ForeignKey(PlayerGroup, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    player_image = models.ImageField(upload_to="players/player_images")
    content = models.CharField(max_length=1000, help_text="BOLD: //x// to make x bold ................. "
                                                          "LINK: --x@/link@-- to go page link with text x..................."
                                                          "NEXT LINE: ==")
    scout_image = models.ImageField(upload_to="players/scout_images")

    def __str__(self):
        return self.name


class TipGroup(models.Model):
    title = models.CharField(max_length=50)
    keywords = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Tip(models.Model):
    group = models.ForeignKey(TipGroup, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    tip_image = models.ImageField(upload_to="players/player_images", blank=True, null=True)
    content = models.CharField(max_length=1000, help_text="BOLD: //x// to make x bold ................. "
                                                          "LINK: --x@/link@-- to go page link with text x..................."
                                                          "NEXT LINE: ==")

    def __str__(self):
        return self.name

guide/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import ListView

from . import models
from .models import Sideshow, CounterTactic, BestTactic, CounterTacticWeaker, CounterTacticStronger,\
    BeginnerTip, PlayerGroup, Player, TipGroup, Tip, ThankYou


def home(request):
    sideshows = Sideshow.objects.all()
    return render(request, 'guide/home.html', {'sideshows': sideshows})


def counter_tactics(request):
    counter_tactics = CounterTactic.objects.all()
    best_tactics = BestTactic.objects.all()
    counter_tactics_weaker = CounterTacticWeaker.objects.all()
    counter_tactics_stronger = CounterTacticStronger.objects.all()
    context = {
        'counter_tactics': counter_tactics,
        'best_tactics': best_tactics,
        'counter_tactics_weaker': counter_tactics_weaker,
        'counter_tactics_stronger': counter_tactics_stronger,
    }
    return render(request, 'guide/counter-tactics.html', context)


def overall_tactics(request):
    best_tactics = BestTactic.objects.all()
    context = {
        'best_tactics': best_tactics,
    }
    return render(request, 'guide/overall-tactics.html', context)


def counter_tactic_detail(request, title):
    title = title.replace("_", " ")
    counter_tactics = CounterTactic.objects.filter(title=title)
    best_tactics = BestTactic.objects.all()
    counter_tactics_weaker = CounterTacticWeaker.objects.all()
    counter_tactics_stronger = CounterTacticStronger.objects.all()
    context = {
        'counter_tactics': counter_tactics,
        'best_tactics': best_tactics,
        'counter_tactics_weaker': counter_tactics_weaker,
        'counter_tactics_stronger': counter_tactics_stronger,
    }
    return render(request, 'guide/tactics-detail.html', context)


def beginners_guide(request):
    tips = BeginnerTip.objects.all()
    context = {
        'tips': tips,
    }
    return render(request, 'guide/beginners_guide.html', context)


def players(request):
    player_groups = PlayerGroup.objects.all()
    players = Player.objects.all()
    context = {
        'player_groups': player_groups,
        'players': players,
    }
    return render(request, 'guide/players.html', context)


def tips(request):
    tip_groups = TipGroup.objects.all()
    tips = Tip.objects.all()
    context = {
        'tip_groups': tip_groups,
        'tips': tips,
    }
    return render(request, 'guide/tips.html', context)


def terms_of_use(request):
    return render(request, 'guide/terms_of_use.html')


def thank_you(request):
    supporters = ThankYou.objects.all()
    return render(request, 'guide/thank_you.html', {'supporters': supporters})

guide/templates/guide/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'guide/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://kit.fontawesome.com/6d8917c4d7.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name=”description” content="Learn how to beat every opponent in Online Soccer Manager by using the perfect tactics.
    Find useful tips and tricks about transfers, tactics and training and master the game!">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar closed" id="navbar">
        <div class="logo">
            <a href="{% url 'home' %}">OSMGuide</a>
        </div>
        <div class="menu-btn">
            <div class="menu-btn__burger"></div>
        </div>
        <br>
        <ul id="pagelinks" class="pagelinks">
            <li><a class="pagelink" href="{% url 'home' %}">Home</a></li>
            <li><a class="pagelink" href="{% url 'counter-tactics' %}">Tactics</a></li>
            <li><a class="pagelink" href="{% url 'beginners_guide' %}">Beginner's Guide</a></li>
            <li><a class="pagelink" href="{% url 'players' %}">Players</a></li>
            <li><a class="pagelink" href="{% url 'tips' %}">Tips</a></li>
        </ul>
    </nav>
    <main id="main">


        {% block content %}

        {% endblock %}


    </main>

    <article class="join">
        <h2>Join Today!</h2>
        <p>Enter your Email adresse to get the latest news about OSM and improve your play</p>
        <form action="">
            <input type="email" class="email" name="email" placeholder="Type email & hit submit" required>
            <input type="submit" value="Submit" class="submit">
            <input type="checkbox" name="agree" class="agree" id="agree" required>
            <label for="agree">I agree the <a href="/terms_of_use" class="terms_of_use">terms and conditions</a></label>
        </form>
    </article>

    <footer>
        <p class="copyright"><a href="/terms_of_use" class="terms_conditions">Terms and Conditions</a><a href="#about" class="about">About</a><a
                href="#contact" class="contact">Contact</a></p>
    </footer>

    <script src="{% static 'guide/animations.js' %}"></script>
</body>
</html>

guide/templates/guide/beginners_guide.html
{% extends "guide/base.html" %}
{% load static %}
{% block title %}OSM Guide - Beginner's Guide: Get started with Online Soccer Manager{% endblock %}

{% block content %}

    <article class="beginners_guide">
        <h3 class="page_title">Beginner's Guide</h3>
        {% for tip in tips %}
            <section class="beginner_tip">
                <h6>Beginner tip {{ forloop.counter }}</h6>
                <h4>{{ tip.title }}</h4>
                <img class="beginner_tip_image" src="{{ tip.image.url }}" alt="Beginners Guide Tip - {{ tip.title }}">
                <p class="beginners_guide_content content">{{ tip.content }}</p>
            </section>
        {% endfor %}
    </article>

<link rel="stylesheet" type="text/css" href="{% static 'guide/beginners_guide_style.css' %}">
<script src="{% static 'guide/beginners_guide_animations.js' %}"></script>

{% endblock %}

guide/templates/guide/counter-tactics.html
{% extends "guide/base.html" %}
{% load static %}
{% block title %}Best Tactic 2020 for Online Soccer Manager - OSM Guide{% endblock %}

{% block content %}
    <article class="secondary_navbar">
        <h4 id="counter_tactics_nav" class="counter_tactics_nav" onclick="counterTactics()">Counter Tactics</h4>
        <h4 id="overall_tactics_nav" class="overall_tactics_nav" onclick="overallTactics()">Overall Tactics</h4>
        <div class="grey_line"></div>
        <div id="blue_line" class="blue_line_counter"></div>
    </article>
    <article class="counter_tactics" id="counter_tactics">
        <input type="text" class="search" id="search_tactics" onkeyup="searchTactics()" placeholder="Search for opponent's formation ...">
        <p class="description search_description" id="search_tactics_description">Enter the formation of your opponent in the search bar above.
            We will find the best tactic to beat your opponent.
        </p>
        {% for counter_tactic in counter_tactics %}
            <div id="counter_tactic_{{ forloop.counter }}" class="tactic">
                <p class="counter_tactic_id">{{ counter_tactic.id }}</p>
                <h5 class="counter_tactic_title" id="counter_tactic_title_{{ forloop.counter }}">{{ counter_tactic.title }}</h5>
                <h6 class="weaker_opponent_nav" id="weaker_opponent_nav" onclick="weakerOpponent({{ forloop.counter0 }})">weaker opponent</h6>
                <h6 class="stronger_opponent_nav" id="stronger_opponent_nav" onclick="strongerOpponent({{ forloop.counter0 }})">stronger opponent</h6>
                {% for counter_tactic_weaker in counter_tactic.countertacticweaker_set.all %}
                    <section class="weaker_opponent" id="weaker_opponent">
                        <p class="formation_text">Against a weaker team you should choose <span class="bold">{{ counter_tactic_weaker.formation_text }}</span>
                            as your formation</p>
                        <img src={{ counter_tactic_weaker.formation_image.url }} class="formation_image" alt="How to beat {{ counter_tactic.title }} - formation">
                        <p class="style_of_play_text">Your style of play should be <span class="bold">{{ counter_tactic_weaker.style_of_play_text }}</span></p>
                        <img src={{ counter_tactic_weaker.style_of_play_image.url }} class="style_of_play_image" alt="How to beat {{ counter_tactic.title }} - style of play">
                        <p class="line_tactics_text">Your line tactics have to be adjusted as follows</p>
                        <img src={{ counter_tactic_weaker.line_tactics_image.url }} class="line_tactics_image">
                        <p class="marking_offside_text">Marking and and offside play should also be adjusted</p>
                        <img src={{ counter_tactic_weaker.marking_offside_image.url }} class="marking_offside_image">
                        <p class="tackling_index_text">The sliders have to be set like this</p>
                        <img src={{ counter_tactic_weaker.tackling_index_image.url }} class="tackling_index_image">
                    </section>
                {% endfor %}
                {% for counter_tactic_stronger in counter_tactic.countertacticstronger_set.all %}
                    <section class="stronger_opponent" id="stronger_opponent">
                        <p class="formation_text">Against a stronger team you should choose <span class="bold">{{ counter_tactic_stronger.formation_text }}</span>
                            as your formation</p>
                        <img src={{ counter_tactic_stronger.formation_image.url }} class="formation_image">
                        <p class="style_of_play_text">Your style of play should be <span class="bold">{{ counter_tactic_stronger.style_of_play_text }}</span></p>
                        <img src={{ counter_tactic_stronger.style_of_play_image.url }} class="style_of_play_image">
                        <p class="line_tactics_text">Your line tactics have to be adjusted as follows</p>
                        <img src={{ counter_tactic_stronger.line_tactics_image.url }} class="line_tactics_image">
                        <p class="marking_offside_text">Marking and and offside play should also be adjusted</p>
                        <img src={{ counter_tactic_stronger.marking_offside_image.url }} class="marking_offside_image">
                        <p class="tackling_index_text">The sliders have to be set like this</p>
                        <img src={{ counter_tactic_stronger.tackling_index_image.url }} class="tackling_index_image">
                    </section>
                {% endfor %}
            </div>
        {% endfor %}
    </article>


<link rel="stylesheet" type="text/css" href="{% static 'guide/tactics_style.css' %}">
<script src="{% static 'guide/tactics_animations.js' %}"></script>

{% endblock %}

guide/templates/guide/home.html
{% extends "guide/base.html" %}
{% block title %}OSM Guide: Best Tactics, Beginner's Guide, Tips and more for Online Soccer Manager{% endblock %}
{% load static %}

{% block content %}
    <h3 class="page_title">Home</h3>
    <article class="sideshow-container">
        {% for sideshow in sideshows %}
        <a href="{{ sideshow.link }}">
            <section class="rounded_corners sideshow fade">
                <img src={{ sideshow.image.url }} alt="sideshow image" class="sideshow_img">
                <h4>{{ sideshow.title }}</h4>
                <p>{{ sideshow.content }}</p>
            </section>
        </a>
        {% endfor %}
    </article>
    <article class="links">
        <h3>Master the game</h3>
        <section class="tactics_link">
            <a href="/tactics/counter-tactics/" >
                <div class="rounded_corners">
                    <img src="media/home_images/tactics.jpg"alt="OSM tactics" class="rounded_corners_img">
                    <p>Tactics</p>
                </div>
            </a>
        </section>
        <section class="players_link">
            <a href="/players" >
                <div class="rounded_corners">
                    <img src="media/home_images/players.jpg" alt="OSM players picture" class="rounded_corners_img">
                    <p>Players</p>
                </div>
            </a>
        </section>
        <section class="tips_link">
            <a href="/tips" >
                <div class="rounded_corners">
                    <img src="media/home_images/tips.jpg" alt="OSM tips picture" class="rounded_corners_img">
                    <p>Tips</p>
                </div>
            </a>
        </section>
        <section class="beginners_guide_link">
            <a href="/beginners_guide" >
                <div class="rounded_corners">
                    <img src="media/home_images/beginners_guide.jpg" alt="OSM beginners guide picture" class="rounded_corners_img">
                    <p>Beginner's Guide</p>
                </div>
            </a>
        </section>
    </article>
    <article class="thank_you_container">
        <a href="/thank_you">
            <section class="rounded_corners thank_you">
                <img src="media/home_images/stadium.PNG" alt="thank you for your support image" class="thank_you_img">
                <h4>Thank you for your great support!</h4>
            </section>
        </a>
    </article>

<script src="{% static 'guide/home_animations.js' %}"></script>

{% endblock content %}

guide/templates/guide/overall-tactics.html
{% extends "guide/base.html" %}
{% load static %}
{% block title %}Best Tactic 2020 for Online Soccer Manager - OSM Guide{% endblock %}

{% block content %}
    <article class="secondary_navbar">
        <h4 id="counter_tactics_nav" class="counter_tactics_nav" onclick="counterTactics()">Counter Tactics</h4>
        <h4 id="overall_tactics_nav" class="overall_tactics_nav" onclick="overallTactics()">Overall Tactics</h4>
        <div class="grey_line"></div>
        <div id="blue_line" class="blue_line"></div>
    </article>
    <article class="counter_tactics" id="counter_tactics">
        <input type="text" class="search" id="search_tactics" onkeyup="searchTactics()" placeholder="Search for opponent's formation ...">
        <p class="description search_description" id="search_tactics_description">Enter the formation of your opponent in the search bar above.
            We will find the best tactic to beat your opponent.
        </p>
        {% for counter_tactic in counter_tactics %}
            <div id="counter_tactic_{{ forloop.counter }}" class="tactic">
                <p class="counter_tactic_id">{{ counter_tactic.id }}</p>
                <h5 class="counter_tactic_title" id="counter_tactic_title_{{ forloop.counter }}">{{ counter_tactic.title }}</h5>
                <h6 class="weaker_opponent_nav" id="weaker_opponent_nav" onclick="weakerOpponent({{ forloop.counter0 }})">weaker opponent</h6>
                <h6 class="stronger_opponent_nav" id="stronger_opponent_nav" onclick="strongerOpponent({{ forloop.counter0 }})">stronger opponent</h6>
                {% for counter_tactic_weaker in counter_tactic.countertacticweaker_set.all %}
                    <section class="weaker_opponent" id="weaker_opponent">
                        <p class="formation_text">Against a weaker team you should choose <span class="bold">{{ counter_tactic_weaker.formation_text }}</span>
                            as your formation</p>
                        <img src={{ counter_tactic_weaker.formation_image.url }} class="formation_image" alt="How to beat {{ counter_tactic.title }} - formation">
                        <p class="style_of_play_text">Your style of play should be <span class="bold">{{ counter_tactic_weaker.style_of_play_text }}</span></p>
                        <img src={{ counter_tactic_weaker.style_of_play_image.url }} class="style_of_play_image" alt="How to beat {{ counter_tactic.title }} - style of play">
                        <p class="line_tactics_text">Your line tactics have to be adjusted as follows</p>
                        <img src={{ counter_tactic_weaker.line_tactics_image.url }} class="line_tactics_image">
                        <p class="marking_offside_text">Marking and and offside play should also be adjusted</p>
                        <img src={{ counter_tactic_weaker.marking_offside_image.url }} class="marking_offside_image">
                        <p class="tackling_index_text">The sliders have to be set like this</p>
                        <img src={{ counter_tactic_weaker.tackling_index_image.url }} class="tackling_index_image">
                    </section>
                {% endfor %}
                {% for counter_tactic_stronger in counter_tactic.countertacticstronger_set.all %}
                    <section class="stronger_opponent" id="stronger_opponent">
                        <p class="formation_text">Against a stronger team you should choose <span class="bold">{{ counter_tactic_stronger.formation_text }}</span>
                            as your formation</p>
                        <img src={{ counter_tactic_stronger.formation_image.url }} class="formation_image">
                        <p class="style_of_play_text">Your style of play should be <span class="bold">{{ counter_tactic_stronger.style_of_play_text }}</span></p>
                        <img src={{ counter_tactic_stronger.style_of_play_image.url }} class="style_of_play_image">
                        <p class="line_tactics_text">Your line tactics have to be adjusted as follows</p>
                        <img src={{ counter_tactic_stronger.line_tactics_image.url }} class="line_tactics_image">
                        <p class="marking_offside_text">Marking and and offside play should also be adjusted</p>
                        <img src={{ counter_tactic_stronger.marking_offside_image.url }} class="marking_offside_image">
                        <p class="tackling_index_text">The sliders have to be set like this</p>
                        <img src={{ counter_tactic_stronger.tackling_index_image.url }} class="tackling_index_image">
                    </section>
                {% endfor %}
            </div>
        {% endfor %}
    </article>

    <article class="overall_tactics" id="overall_tactics">
        <p class="description">Generally, you should choose your own tactic by looking at your opponent's one and picking the best counter tactic.
            However, if you want to spend less time, choose one of the best overall tactics that are listed here.</p>
        {% for best_tactic in best_tactics %}
            <div id="tactic_{{ forloop.counter }}" class="tactic">
                <h5 id="tactic_title_{{ forloop.counter }}">{{ best_tactic.title }}</h5>
                    <section><br>
                        <p class="formation_text">If you want to play this tactic, you should use <span class="bold">{{ best_tactic.formation_text }}</span>
                            as your formation:</p>
                        <img src={{ best_tactic.formation_image.url }} class="formation_image">
                        <p class="style_of_play_text">Your style of play should be <span class="bold">{{ best_tactic.style_of_play_text }}:</span></p>
                        <img src={{ best_tactic.style_of_play_image.url }} class="style_of_play_image">
                        <p class="line_tactics_text">Your line tactics have to be adjusted as follows:</p>
                        <img src={{ best_tactic.line_tactics_image.url }} class="line_tactics_image">
                        <p class="marking_offside_text">Marking and and offside play should also be adjusted:</p>
                        <img src={{ best_tactic.marking_offside_image.url }} class="marking_offside_image">
                        <p class="tackling_index_text">The sliders have to be set like this:</p>
                        <img src={{ best_tactic.tackling_index_image.url }} class="tackling_index_image">
                    </section>
                {% endfor %}
            </div>
    </article>

<link rel="stylesheet" type="text/css" href="{% static 'guide/tactics_style.css' %}">
<script src="{% static 'guide/tactics_animations.js' %}"></script>

{% endblock %}

guide/templates/guide/players.html
{% extends "guide/base.html" %}
{% block title %}OSM Guide - Find the best Playes{% endblock %}
{% load static %}

{% block content %}

    <article class="players" id="players">
        <h3 class="page_title">Players</h3>
        <input type="text" class="search" id="search_players" onkeyup="searchPlayers(event)" placeholder="Search for a player group or a player...">
        <p class="description search_description" id="search_players_description">Type a player group or a player in the search bar above.
        </p>
        {% for player_group in player_groups %}
            <div id="player_group_{{ forloop.counter }}" class="player_group">
                <h4 id="player_group_title_{{ forloop.counter }}">{{ player_group.title }}</h4>
                <p class="invisible keywords" id="keywords">{{ player_group.keywords }}</p>
                {% for player in player_group.player_set.all %}
                    <section class="player" id="player_{{ forloop.counter }}">
                        <h5 class="player_name" id="player_name_{{ forloop.counter }}">{{ player.name }}</h5>
                        <img src={{ player.player_image.url }} class="player_image" alt="OSM Players - {{ player.name }}">
                        <p class="player_content content">{{ player.content }}</p>
                        <img src={{ player.scout_image.url }} class="scout_image">
                    </section>
                {% endfor %}
            </div>
        {% endfor %}
    </article>

<link rel="stylesheet" type="text/css" href="{% static 'guide/players_style.css' %}">
<script src="{% static 'guide/players_animations.js' %}"></script>

{% endblock %}

guide/templates/guide/thank_you.html
{% extends "guide/base.html" %}
{% block title %}OSM Guide - Thank you for your support!{% endblock %}
{% load static %}

{% block content %}
    <h3 class="page_title">Thank You!</h3>
    {% for supporter in supporters %}
        <p class="thank_you_text">{{ supporter.name }}</p>
    {% endfor %}
{% endblock %}

guide/templates/guide/tips.html
{% extends "guide/base.html" %}

{% load static %}

{% block content %}

    <article class="tips" id="tips">
        <h3 class="page_title">Tips</h3>
        <input type="text" class="search" id="search_tips" onkeyup="searchTips(event)" placeholder="Search for tips...">
        <p class="description search_description" id="search_tips_description">
            Type the category for which you want to find tips into the searchbar above
        </p>
        {% for tip_group in tip_groups %}
            <div id="tip_group_{{ forloop.counter }}" class="tip_group">
                <h4 id="tip_group_title_{{ forloop.counter }}">{{ tip_group.title }}</h4>
                <p class="invisible keywords" id="keywords">{{ tip_group.keywords }}</p>
                {% for tip in tip_group.tip_set.all %}
                    <section class="tip" id="tip_{{ forloop.counter }}">
                        <h5 class="tip_name" id="tip_name_{{ forloop.counter }}">{{ tip.name }}</h5>
                        {% if tip.tip_image.url %}
                            <img src={{ tip.tip_image.url }} class="tip_image" alt="OSM Tips - {{ tip.name }}">
                        {% endif %}
                        <p class="tip_content content">{{ tip.content }}</p>
                    </section>
                {% endfor %}
            </div>
        {% endfor %}
    </article>


<link rel="stylesheet" type="text/css" href="{% static 'guide/tips_style.css' %}">
<script src="{% static 'guide/tips_animations.js' %}"></script>

{% endblock %}